
[functions.validate-session-notes]
enabled = true
verify_jwt = true
import_map = "./functions/validate-session-notes/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/validate-session-notes/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/validate-session-notes/*.html" ]
